#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#
# 井号后面的文字是说明文档，不会被程序读取。
name: 风车大战骑士
# 描述/签名
description: 生活不止眼前的苟且，还有诗和远方

#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/95b0e643fb5f4f349831b1a96fb9c06c~tplv-k3u1fbpfcp-zoom-1.image

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/95b0e643fb5f4f349831b1a96fb9c06c~tplv-k3u1fbpfcp-zoom-1.image


# 菜单中的按钮
navigation:
  - name: 首页
    url: /
  - name: 归档
    url: /archive
  - name: 标签
    url: /tags
  - name: 关于
    url: /about
  - name: 书籍
    url: https://www.sohod.cn/book/

# 每页的文章数
paginate: 20

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo: huyong668 #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: huyong229@163.com 
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: AndreHu88
  instagram: #https://instagram.com/<>
  linkedin: #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username> 
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright(c) 2017 愿你出走半生，归来仍是少年

# 输入Disqus shortname，即可添加评论区，细节可阅读文档。
disqus: Jack  #shortname

# 输入Google Analytics web tracking code
google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url:  http://www.sohod.cn

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: 


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

excerpt_separator: ---
